# Generated by Django 5.1.6 on 2025-02-07 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('completed', models.BooleanField(default=False)),
                ('url_link', models.URLField(blank=True, max_length=300, null=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
