# Generated by Django 5.1.5 on 2025-02-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
