# Generated by Django 5.1.6 on 2025-02-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('title', models.CharField(max_length=100)),
                ('updated_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title', 'updated_date'],
            },
        ),
    ]
