# Generated by Django 5.1.6 on 2025-02-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_alter_saving_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saving',
            name='priority',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
